name: "Publish Python SDK to PyPI"
description: "Publish a Python SDK to PyPI using OIDC trusted publishing"
inputs:
  python-directory:
    description: "Directory containing the Python SDK"
    required: true
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"
  uv-version:
    description: "Version of uv to use for building"
    required: false
  speakeasy_api_key:
    description: "The Speakeasy API key for logging publish events"
    required: true
  github_access_token:
    description: "A GitHub access token"
    required: true
  speakeasy_server_url:
    description: "Speakeasy server URL (internal use)"
    required: false
  working_directory:
    description: "Working directory for Speakeasy CLI commands"
    required: false
  slack_webhook_url:
    description: "Slack webhook URL for failure notifications"
    required: false
runs:
  using: "composite"
  steps:
    - name: Tune GitHub-hosted runner network
      uses: smorimoto/tune-github-hosted-runner-network@bb252dcb5c8609a31087e7993daa086f5a1c0069 # v1
    - name: Checkout sdk-generation-action repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: speakeasy-api/sdk-generation-action
        ref: 788702f013dcd7b0716076b1ce4e5f19be009521
        path: _speakeasy
    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        version: ${{ inputs.uv-version }}
    - name: Build package
      shell: bash
      working-directory: ${{ inputs.python-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish to PyPI (Trusted Publishing)
      id: publish
      shell: bash
      working-directory: ${{ inputs.python-directory }}
      run: |
        uv publish --trusted-publishing always dist/*
    - name: Log publish event
      id: publish-event
      if: always()
      uses: ./_speakeasy
      with:
        github_access_token: ${{ inputs.github_access_token }}
        action: publish-event
        speakeasy_api_key: ${{ inputs.speakeasy_api_key }}
        working_directory: ${{ inputs.working_directory }}
        speakeasy_server_url: ${{ inputs.speakeasy_server_url }}
        target_directory: ${{ inputs.python-directory }}
        registry_name: "pypi"
      env:
        GH_ACTION_RESULT: ${{ steps.publish.outcome }}
    - name: Notify Slack on failure
      if: always() && failure() && inputs.slack_webhook_url != ''
      uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2
      with:
        status: failure
        token: ${{ inputs.github_access_token }}
        notify_when: "failure"
        notification_title: "Failed to publish Python SDK to PyPI"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Run>"
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
    - name: Log result
      id: log-result
      if: always()
      uses: ./_speakeasy
      with:
        github_access_token: ${{ inputs.github_access_token }}
        action: log-result
        speakeasy_api_key: ${{ inputs.speakeasy_api_key }}
        working_directory: ${{ inputs.working_directory }}
        speakeasy_server_url: ${{ inputs.speakeasy_server_url }}
      env:
        GH_ACTION_RESULT: ${{ steps.publish.outcome }}
        GH_ACTION_STEP: publish-pypi
        TARGET_TYPE: "sdk"
