name: "Publish Python SDK to PyPI"
description: "Publish a Python SDK to PyPI using OIDC trusted publishing"
inputs:
  python-directory:
    description: "Directory containing the Python SDK"
    required: true
  python-version:
    description: "Python version to use"
    required: false
    default: "3.10"
  uv-version:
    description: "Version of uv to use for building"
    required: false
  speakeasy_version:
    description: "The version of the Speakeasy CLI to use or 'latest'"
    default: latest
    required: false
  speakeasy_api_key:
    description: "The Speakeasy API key for logging publish events"
    required: true
  github_access_token:
    description: "A GitHub access token"
    required: true
  speakeasy_server_url:
    description: "Speakeasy server URL (internal use)"
    required: false
  working_directory:
    description: "Working directory for Speakeasy CLI commands"
    required: false
  slack_webhook_url:
    description: "Slack webhook URL for failure notifications"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install speakeasy CLI
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh
      env:
        SPEAKEASY_VERSION: ${{ inputs.speakeasy_version }}
    - name: Set up Python
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        version: ${{ inputs.uv-version }}
    - name: Build package
      shell: bash
      working-directory: ${{ inputs.python-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build
    - name: Publish to PyPI (Trusted Publishing)
      id: publish
      shell: bash
      working-directory: ${{ inputs.python-directory }}
      run: |
        uv publish --trusted-publishing always dist/*
    - name: Log publish event
      id: publish-event
      if: always()
      shell: bash
      run: |
        speakeasy ci publish-event
      env:
        SPEAKEASY_API_KEY: ${{ inputs.speakeasy_api_key }}
        SPEAKEASY_SERVER_URL: ${{ inputs.speakeasy_server_url }}
        SPEAKEASY_ENVIRONMENT: github
        INPUT_GITHUB_ACCESS_TOKEN: ${{ inputs.github_access_token }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        INPUT_TARGET_DIRECTORY: ${{ inputs.python-directory }}
        INPUT_REGISTRY_NAME: "pypi"
        GH_ACTION_RESULT: ${{ steps.publish.outcome }}
    - name: Notify Slack on failure
      if: always() && failure() && inputs.slack_webhook_url != ''
      uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2
      with:
        status: failure
        token: ${{ inputs.github_access_token }}
        notify_when: "failure"
        notification_title: "Failed to publish Python SDK to PyPI"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Run>"
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
    - name: Log result
      id: log-result
      if: always()
      shell: bash
      run: |
        speakeasy ci log-result
      env:
        SPEAKEASY_API_KEY: ${{ inputs.speakeasy_api_key }}
        SPEAKEASY_SERVER_URL: ${{ inputs.speakeasy_server_url }}
        SPEAKEASY_ENVIRONMENT: github
        INPUT_GITHUB_ACCESS_TOKEN: ${{ inputs.github_access_token }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
        GH_ACTION_RESULT: ${{ steps.publish.outcome }}
        GH_ACTION_STEP: publish-pypi
        TARGET_TYPE: "sdk"
