name: Generate Multi-Language SDKs
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      language:
        description: Language to generate
        default: java
      target:
        description: some target
        default: staging-public-java
      mode:
        description: |-
          The mode to run the workflow in when using the 'generate' action, valid options are 'direct' or 'pr', defaults to 'direct'.
          This is intended to be used along with the `action` input to determine the current action step to run.
            - 'direct' mode will generally create a branch to generate the SDK on then merge this directly to the branch the workflow is configure to run on (normally 'main' or 'master') after compilation is successful.
            - 'pr' will create a branch to generate the SDK on then create a pull request to merge this branch to the branch the workflow is configure to run on (normally 'main' or 'master') after compilation is successful.
          See documentation for more details.
        default: "direct"
        required: false
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: optionally set a specific SDK version
        type: string
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
jobs:
  sdk-generation:
    name: Generate SDK - ${{ inputs.language }}
    runs-on: ubuntu-latest
    outputs:
      resolved_speakeasy_version: ${{ steps.run-workflow.outputs.resolved_speakeasy_version }}
    steps:
      - id: run-workflow
        name: Run Generation Workflow - Java
        uses: speakeasy-api/sdk-generation-action@56a21ab6f9a0c3d91f0cef98e175ab135bb98bc4
        with:
          speakeasy_version: ${{ inputs.speakeasy_version }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          mode: direct
          force: ${{ inputs.force }}
          signed_commits: true
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          output_tests: ${{ inputs.output_tests }}
          speakeasy_server_url: ${{ inputs.speakeasy_server_url }}
          working_directory: ${{ inputs.working_directory }}
          target: ${{ inputs.target }}
          registry_tags: ${{ inputs.registry_tags }}
          push_code_samples_only: ${{ inputs.push_code_samples }}
          set_version: ${{ inputs.set_version || github.event.inputs.set_version }}
          cli_environment_variables: ${{ inputs.environment }}
          pnpm_version: "8.15.9"
          github_repository: ${{ inputs.github_repository }}
          enable_sdk_changelog: ${{ inputs.enable_sdk_changelog }}
      - id: log-result
        name: Log Generation Output - ${{ inputs.language }}
        uses: speakeasy-api/sdk-generation-action@8fedbefd6e4698788457895e05395af81cbe9d8a
        with:
          speakeasy_version: ${{ inputs.speakeasy_version }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: ${{ inputs.working_directory }}
          action: log-result
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
          speakeasy_server_url: ${{ inputs.speakeasy_server_url }}
        env:
          GH_ACTION_RESULT: ${{ job.status }}
          RESOLVED_SPEAKEASY_VERSION: ${{ steps.run-workflow.outputs.resolved_speakeasy_version }}
          GH_ACTION_VERSION: "8fedbefd6e4698788457895e05395af81cbe9d8a"
          GH_ACTION_STEP: ${{ github.job }}