version: "3.9"

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app  # Live code reloading
    stdin_open: true
    tty: true
    container_name: main_container
    environment:
      - INPUT_DEBUG=true
      - INPUT_GITHUB_ACCESS_TOKEN=${GITHUB_TOKEN}
      - GITHUB_SERVER_URL=https://github.com
      - GITHUB_REPOSITORY=speakeasy-api/sdk-generation-action-test-repo
      - GITHUB_REPOSITORY_OWNER=speakeasy-api
      - GITHUB_REF=refs/heads/main
      - GITHUB_OUTPUT=./output.txt
      - GITHUB_WORKFLOW=test
      - GITHUB_WORKSPACE=${PWD}
      - GITHUB_RUN_ID=1
      - GITHUB_RUN_ATTEMPT=1
      - SPEAKEASY_ENVIRONMENT=local
      - SPEAKEASY_API_KEY=${SPEAKEASY_API_KEY}
