on: workflow_call

jobs:
  update-speakeasy-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find branch and commit
        run: |
          COMMIT_HASH=$(git log main --author='speakeasybot' --format=%H -1)
          if [[ -n "$COMMIT_HASH" ]]; then
            git fetch origin
            echo "Most recent speakeasybot hash: $COMMIT_HASH" 
            if git show-ref --verify --quiet refs/heads/speakeasy/main; then
              git checkout speakeasy/main 
              git cherry-pick $COMMIT_HASH
            else
              git checkout -b speakeasy/main $COMMIT_HASH
            fi
            git push origin speakeasy/main
          else
            echo "No previous generation commit found."
          fi
